blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: Bug report
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
